src/Entity/LabInstance.php
<?php

namespace App\Entity;

use Exception;
use App\Entity\Instance;
use UnexpectedValueException;
use App\Entity\DeviceInstance;
use Doctrine\ORM\Mapping as ORM;
use App\Message\InstanceStateMessage;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Collection;
use JMS\Serializer\Annotation as Serializer;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LabInstanceRepository")
 */
class LabInstance extends Instance
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Serializer\Groups({"primary_key"})
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lab", inversedBy="instances")
     * @Serializer\Groups({"lab", "start_lab", "stop_lab", "instance_manager", "instances"})
     */
    protected $lab;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DeviceInstance", mappedBy="labInstance", cascade={"persist", "remove"})
     * @Serializer\Groups({"lab", "start_lab", "stop_lab", "instance_manager", "instances"})
     */
    private $deviceInstances;

    /**
     * @ORM\Column(type="boolean")
     * @Serializer\Groups({"lab", "start_lab", "stop_lab"})
     */
    private $isInterconnected;

    /**
     * @ORM\Column(type="boolean")
     * @Serializer\Groups({"lab", "start_lab", "stop_lab"})
     */
    private $isInternetConnected;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\NetworkSettings", inversedBy="labInstance", cascade={"persist", "remove"})
     */
    private $networkSettings;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Groups({"lab", "start_lab", "stop_lab", "instance_manager", "instances"})
     */
    private $state;

    const SCOPE_STANDALONE = 'standalone';
    const SCOPE_ACTIVITY = 'activity';

    public function __construct()
    {
        parent::__construct();
        $this->deviceInstances = new ArrayCollection();
        $this->scope = self::SCOPE_STANDALONE;
        $this->state = InstanceStateMessage::STATE_CREATING;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLab(): ?Lab
    {
        return $this->lab;
    }

    public function setLab(?Lab $lab): self
    {
        $this->lab = $lab;

        return $this;
    }

    /**
     * Generate a bridge name with instance UUID.
     * 
     * @Serializer\VirtualProperty()
     * @Serializer\Groups({"lab", "start_lab", "stop_lab"})
     * @Serializer\XmlAttribute
     */
    public function getBridgeName(): string
    {
        return "br-" . substr($this->uuid, 0, 8);
    }

    /**
     * Get device instance associated to this lab instance
     *
     * @return DeviceInstance
     */
    public function getDeviceInstance($device): ?DeviceInstance
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq("device", $device));

        $deviceInstance = ($this->deviceInstances !== null) ? $this->deviceInstances->matching($criteria)->first() : null;

        return $deviceInstance ?: null;
    }

    /**
     * Get device instances associated to this lab instance
     *
     * @return Collection|DeviceInstance[]
     */
    public function getDeviceInstances()
    {
        return $this->deviceInstances;
    }

    /**
     * Get device instance associated to this lab instance and the current user
     *
     * @return DeviceInstance
     */
    public function getUserDeviceInstance($device): ?DeviceInstance
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq("device", $device))
            ->andWhere(Criteria::expr()->eq("user", $this->user));

        $deviceInstance = ($this->deviceInstances !== null) ? $this->deviceInstances->matching($criteria)->first() : null;

        return $deviceInstance ?: null;
    }

    /**
     * Get device instances associated to this lab instance and the current user
     *
     * @return Collection|DeviceInstance[]
     */
    public function getUserDeviceInstances()
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq("user", $this->user));

        $deviceInstances = $this->deviceInstances->matching($criteria);

        return $deviceInstances;
    }

    public function isInternetConnected(): ?bool
    {
        return $this->isInternetConnected;
    }

    public function setInternetConnected(bool $isInternetConnected): self
    {
        $this->isInternetConnected = $isInternetConnected;

        return $this;
    }

    public function isInterconnected(): ?bool
    {
        return $this->isInterconnected;
    }

    public function setInterconnected(bool $isInterconnected): self
    {
        $this->isInterconnected = $isInterconnected;

        return $this;
    }

    public function addDeviceInstance(DeviceInstance $deviceInstance): self
    {
        if (!$this->deviceInstances->contains($deviceInstance)) {
            $this->deviceInstances[] = $deviceInstance;
            $deviceInstance->setLabInstance($this);
        }

        return $this;
    }

    public function removeDeviceInstance(DeviceInstance $deviceInstance): self
    {
        if ($this->deviceInstances->contains($deviceInstance)) {
            $this->deviceInstances->removeElement($deviceInstance);
            // set the owning side to null (unless already changed)
            if ($deviceInstance->getLabInstance() === $this) {
                $deviceInstance->setLabInstance(null);
            }
        }

        return $this;
    }

    public function hasDeviceInstance(): bool
    {
        return $this->deviceInstances->count() > 0;
    }

    public function getNetworkSettings(): ?NetworkSettings
    {
        return $this->networkSettings;
    }

    public function setNetworkSettings(?NetworkSettings $networkSettings): self
    {
        $this->networkSettings = $networkSettings;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function isCreated(): ?bool
    {
        return $this->state === InstanceStateMessage::STATE_CREATED;
    }

    /**
     * Creates all sub-instances from Lab descriptor. This does not record them in the database.
     */
    public function populate()
    {
        if (!$this->lab) {
            throw new Exception('No lab is associated to this instance.');
        }

        foreach ($this->lab->getDevices() as $device) {
            $deviceInstance = DeviceInstance::create()
                ->setDevice($device)
                ->setLabInstance($this)
                ->setOwnedBy($this->ownedBy);

            switch ($this->ownedBy) {
                case self::OWNED_BY_USER:
                    $deviceInstance->setUser($this->user);
                    break;

                case self::OWNED_BY_GROUP:
                    $deviceInstance->setGroup($this->_group);
                    break;
            }

            $deviceInstance->populate();

            $device->addInstance($deviceInstance);
            $this->addDeviceInstance($deviceInstance);
        }
    }
}

templates/activity/index.html.twig
{% extends 'dashboard.base.html.twig' %}

{% block breadcrumbs %}
    {%- set breadcrumbs = breadcrumbs|merge({ 'Activities': path('activities') }) -%}
    {{ parent() }}
{% endblock %}

{% block sidebar %}
    {% set category = 'activities' %}
    {{ parent() }}
{% endblock %}

{% block wrapper %}
    <div class="top-panel">
        <div class="quick-actions">
            {% if is_granted('ROLE_ADMINISTRATOR') %}
                <a class="btn btn-success btn-block" role="button" href="{{
                path('new_activity') }}">{{ 'New Activity'|trans }}</a>
            {% endif %}
        </div>
        <ul class="nav-links nav nav-tabs">
            {# <li><a href="#"><span>Started</span> <span class="badge badge-pill">0</span></a></li>
            <li><a href="#"><span>Stopped</span> <span class="badge badge-pill">0</span></a></li> #}
            <li class="active">
                <a href="#">
                    <span>All</span> <span class="badge badge-pill">{{ activities|length }}</span>
                </a>
            </li>
        </ul>
    </div>
    {# <div class="search-panel">
        <form action="{{ path('activities') }}" method="GET">
            <input type="search" class="form-control input-sm" name="search"
            placeholder="Search by name"
            spellcheck="false" value="{{ search|default('') }}" type="search">
        </form>
    </div> #}
    <div class="labs-panel">
    {% for activity in activities %}
        <div class="wrapper d-flex align-items-center p-3 {% if not loop.last %}border-bottom{% endif %} lab-item">
            <div class="lab-item-left d-flex flex-column">
                <div>
                    <a href="{{ path('show_activity', {'id': activity.id}) }}" class="lab-item-name">
                        {{- activity.name -}}
                    </a>
                </div>
                <div class="lab-item-infos text-muted">
                    #{{ activity.id }} · created
                    <span class="timeago" datetime="{{ activity.createdAt|date('m/d/Y H:i:s') }}" data-toggle="tooltip" data-placement="bottom" title="{{ activity.createdAt|date('M d, Y h:ia') }}"></span>
                    by
                    <a href="{{ path('activities', app.request.query|merge({author: activity.author.id})) }}" data-toggle="tooltip" data-placement="top" title="See all activites by {{activity.author.name}}">
                        <img src="/users/{{activity.author.id}}/picture?size=17" alt="{{activity.author.name}}" class="rounded-circle v-bottom" />
                        <span class="lab-item-author" >{{ activity.author.name }}</span>
                    </a>
                </div>
            </div>
        </div>
    {% endfor %} 
    </div>
    
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {# {{ encore_entry_script_tags('activity') }} #}
{% endblock %}

templates/activity/new.html.twig
{% extends 'activity/index.html.twig' %}

{% block breadcrumbs %}
    {% set breadcrumbs = app.request.uri ends with 'edit' ? breadcrumbs : breadcrumbs|merge({ 'New': path('new_activity') }) %}
    {{ parent() }}
{% endblock %}

{%- set edit = app.request.uri ends with 'edit' -%}

{% block wrapper %}
    <div class="content-title">
        <div class="content-title-infos">
            <h1>
                {% if app.request.uri ends with 'edit' %}
                    {{ 'Edit activity'|trans }}: {{ activity.name }}
                {% else %}
                    {{ 'New activity'|trans }}
                {% endif %}
            </h1>
        </div>
    </div>
    <div class="content-body">
        {{ form_start(activityForm) }}
            {{ form_errors(activityForm) }}

            {{ form_row(activityForm.name) }}
            {{ form_row(activityForm.description) }}
            {{ form_row(activityForm.lab) }}
            {{ form_row(activityForm.internetAllowed) }}
            {{ form_row(activityForm.interconnected) }}

            <div class="form-group row">
                <legend class="col-sm-2 col-form-label required text-right">Group</legend>
                <div class="col-sm-10">
                    {{- react_component('GroupSelect', {props: {"fieldName": "activity[_group]"}}) -}}
                </div>
            </div>
        {{ form_end(activityForm) }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('activity') }}
{% endblock %}

templates/activity/view.html.twig
{% extends 'activity/index.html.twig' %}

{% block breadcrumbs %}
    {%- set breadcrumbs = breadcrumbs|merge({ ("#" ~ activity.id): path('show_activity', {'id': activity.id}) }) -%}
    {{ parent() }}
{% endblock %}

{% block wrapper %}
    <div class="content-title">
        <div class="content-title-infos">
            <h1>{{ activity.name }}</h1>
        </div>
        <div class="content-title-actions">
            {% if activity.lab is not null %}
                {% set lab_on=false %}  
                {% if labInstance is null %}
                    <a href="{{ path('start_activity', {'id': activity.id}) }}" class="btn btn-primary">Start activity</a>
                {% else %}
                    Activity already started - 
                    <a href="{{ path('show_lab', {'id': activity.lab.id}) }}" class="btn btn-default">Go to Lab</a>
                    {% set lab_on=true %}                      
                {% endif %}
                {% if  is_granted("ROLE_TEACHER") and not lab_on %}
                    <a href="{{ path('show_lab', {'id': activity.lab.id}) }}" class="btn btn-default">Go to Lab</a>
                {% endif %}
            {% endif %}
            {% if is_granted("ROLE_ADMINISTRATOR") %}
                <a href="{{ path('edit_activity', {'id': activity.id}) }}" class="btn btn-secondary" role="button"><i class="fa fa-edit"></i> {{ 'Edit'|trans }}</a>
                <a href="{{ path('delete_activity', {'id': activity.id}) }}" class="btn btn-danger" role="button">Delete</a>
            {% endif %}
        </div>
    </div>

    {{ react_component('InstanceManager', {props: {user: app.user.email}}) }}

    <div class="content-body">     
        {{ activity.description|markdown }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('activity') }}
{% endblock %}